import React from "react";
import Lightbox from "../components/Lightbox";
import Head from 'next/head'

const galeria = () => {
  return (
    <section className="mt-[95px]">
      <Head>
        <title>VFX - Montagens Industriais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-3.svg" />
      </Head>
      <div className="grid text-center justify-center">
        <h1 className="my-10">Exemplos de Trabalhos</h1>
      </div>
      <div>
        <Lightbox />
      </div>
    </section>
  );
};

export default galeria;
