import Head from "next/head";
import Carousel from "../components/Carousel";
import Empresa from "../components/Empresa";
import Services from "../components/Services";
import Valores from "../components/Valores";
import SimpleMap from "../components/SimpleMap";
import Gestão from "../components/Gestão";
import Projects from "../components/Projects";
import Metodos from "../components/Metodos";
import Qualidade from "../components/Qualidade";
import Segurança from "../components/Segurança";
import Clientes from "../components/Clientes";


export default function Home() {
  return (
    <div>
      <Head>
        <title>VFX - Montagens Industriais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-3.svg" />
      </Head>
      <Carousel />
      <Empresa />
      <Services />
      <Valores />
      <SimpleMap />
      <Gestão />
      <Projects />
      <Metodos />
      <Qualidade />
      <Segurança />
      <Clientes />
    </div>
  );
}
