import Head from 'next/head'
import Carousel from '../components/Carousel'
import NossaHistoria from '../components/NossaHistoria'
import FaleComRepresentante from '../components/FaleComRepresentante'
import Instagram from '../components/Instagram'
import QuemSomos from '../components/QuemSomos'
import HowCanWeHelp from '../components/HowCanWeHelp'
import Services from '../components/Services'


export default function Home() {
  return (
    <div>
      <Head>
        <title>VFX - Montagens Industriais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <Carousel /> 
      <QuemSomos/>
      <HowCanWeHelp/>
      <Services />
    </div>
  )
}
