import React from "react";
import TrabalheConosco from "../components/TrabalheConosco";
import Head from "next/head";

const trabalheConosco = () => {
  return (
    <div>
      <Head>
        <title>VFX - Montagens Industriais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-3.svg" />
      </Head>
      <TrabalheConosco />
    </div>
  );
};

export default trabalheConosco;
